
package br.com.caelum.estoque.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.10
 * 2021-06-10T14:52:40.731-03:00
 * Generated source version: 3.3.10
 */

@WebFault(name = "AutorizacaoFault", targetNamespace = "http://ws.estoque.caelum.com.br/")
public class AutorizacaoFault extends Exception {

    private java.lang.String faultInfo;

    public AutorizacaoFault() {
        super();
    }

    public AutorizacaoFault(String message) {
        super(message);
    }

    public AutorizacaoFault(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public AutorizacaoFault(String message, java.lang.String autorizacaoFault) {
        super(message);
        this.faultInfo = autorizacaoFault;
    }

    public AutorizacaoFault(String message, java.lang.String autorizacaoFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = autorizacaoFault;
    }

    public java.lang.String getFaultInfo() {
        return this.faultInfo;
    }
}
